version: '3.8'

networks:
  internal:
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    expose:
      - '5432'
    ports:
      - '5432:5432'
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  cpp-app:
    container_name: cpp-app
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - internal

  electron-frontend:
    container_name: electron-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile # Ensure this Dockerfile is the one prepared for Electron
    ports:
      - '8080:8080' # Map the port if needed, otherwise remove this line
    networks:
      - internal
    depends_on:
      - cpp-app # If the frontend depends on the backend app